pub const RATIO: f32 = 720.0 / 1280.0;
pub const WINDOW_HEIGHT: f32 = 1280.;
pub const WINDOW_WIDTH: f32 = WINDOW_HEIGHT * RATIO;
/// where the game is played
pub const INNER_WINDOW_PADDING_Y: f32 = 150.;
pub const INNER_WINDOW_PADDING_X: f32 = 50.;
pub const INNER_WINDOW_Y_OFFSET: f32 = -100.;
pub const INNER_WINDOW_HEIGHT: f32 = WINDOW_HEIGHT - 2. * INNER_WINDOW_PADDING_Y;
pub const INNER_WINDOW_WIDTH: f32 = WINDOW_WIDTH - 2. * INNER_WINDOW_PADDING_X;
/// real coordinates
/// 0,0 is the center of the screen
pub const INNER_WINDOW_X_MIN: f32 = -INNER_WINDOW_WIDTH / 2.;
pub const INNER_WINDOW_X_MAX: f32 = INNER_WINDOW_X_MIN + INNER_WINDOW_WIDTH;
pub const INNER_WINDOW_Y_MIN: f32 = -INNER_WINDOW_HEIGHT / 2. + INNER_WINDOW_Y_OFFSET;
pub const INNER_WINDOW_Y_MAX: f32 = INNER_WINDOW_Y_MIN + INNER_WINDOW_HEIGHT;
pub const FRAME_Z: f32 = 500.0;

pub const JUDGE_LINE_WIDTH: f32 = INNER_WINDOW_WIDTH;
pub const JUDGE_LINE_HEIGHT: f32 = 50.;

pub const JUDGE_LINE_POSITION: f32 = INNER_WINDOW_Y_MIN + 140.;

pub const TOP_SLOT_COUNT: u32 = 3;
pub const TOP_SLOT_COUNT_F: f32 = TOP_SLOT_COUNT as f32;
pub const TOP_SLOT_SIZE: f32 = OBJECT_SIZE;

pub const TOP_SLOT_PADDING: f32 = 50. + TOP_SLOT_SIZE / 2.;
pub const TOP_SLOT_START_X: f32 = INNER_WINDOW_X_MIN + TOP_SLOT_PADDING;
pub const TOP_SLOT_END_X: f32 = INNER_WINDOW_X_MAX - TOP_SLOT_PADDING;
pub const TOP_SLOT_SPACING: f32 = (TOP_SLOT_END_X - TOP_SLOT_START_X) / (TOP_SLOT_COUNT_F - 1.0);
pub const TOP_SLOT_Y: f32 = INNER_WINDOW_Y_MIN + 340.;

pub const TOP_SPAWN_PADDING: f32 = 200.;
pub const TOP_SPAWN_X_START: f32 = INNER_WINDOW_X_MIN + TOP_SPAWN_PADDING;
pub const TOP_SPAWN_X_END: f32 = INNER_WINDOW_X_MAX - TOP_SPAWN_PADDING;
pub const TOP_SPAWN_X_SPACING: f32 = (TOP_SPAWN_X_END - TOP_SPAWN_X_START) / (TOP_SLOT_COUNT_F - 1.0);


pub const OBJ_TIME: f64 = 0.7;
pub const SPAWN_POSITION: f32 = INNER_WINDOW_Y_MAX + 50.;
pub const OBJECT_Z: f32 = 100.;
pub const OBJECT_Z_DIFF: f32 = 1.0 / 100000.0;

pub const BOTTOM_SLOT_COUNT: u32 = 7;
pub const BOTTOM_SLOT_COUNT_F: f32 = BOTTOM_SLOT_COUNT as f32;

pub const OBJECT_SIZE: f32 = 60.;
pub const BOTTOM_SLOT_PADDING: f32 = 80. + OBJECT_SIZE / 2.;
pub const BOTTOM_SLOT_START_X: f32 = INNER_WINDOW_X_MIN + BOTTOM_SLOT_PADDING;
pub const BOTTOM_SLOT_END_X: f32 = INNER_WINDOW_X_MAX - BOTTOM_SLOT_PADDING;
pub const BOTTOM_SLOT_SPACING: f32 = (BOTTOM_SLOT_END_X - BOTTOM_SLOT_START_X) / (BOTTOM_SLOT_COUNT_F - 1.0);
pub const BOTTOM_SLOT_Y: f32 = JUDGE_LINE_POSITION;

pub const CHAIN_WIDTH: f32 = 8.;
pub const CHAIN_Z: f32 = 90.;
pub const CHAIN_Z_DIFF: f32 = 1.0 / 100000.0;

// audio
pub const AUDIO_DELAY: f64 = 0.1;
pub const VOLUME_SONG: f32 = 0.12;
pub const VOLUME_SFX: f32 = 0.10;